name: GreatHealth CI/CD

on:
  push:
    branches:
      - deployment

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: azure/docker-login@v1
      with:
        login-server: witkamil.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - run: |
        docker build . -t witkamil.azurecr.io/greathealth:${{ github.run_number }}
        docker push witkamil.azurecr.io/greathealth:${{ github.run_number }}
    - uses: azure/webapps-deploy@v2
      with:
        app-name: 'greathealth'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        images: 'witkamil.azurecr.io/greathealth:${{ github.run_number }}'